version: '3.8'

services:
  app:
    image: golang:1.22.5
    container_name: url-shortener
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: go run ./cmd/main.go
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
